### ISSUE TITLE
Data alleen ophalen en opslaan op specfieke tijd

### ISSUE THREAD

**Issue by rohid2000** [rohid2000/tsom-bot#45]
- Data alleen ophalen om 19:28 
- Data alleen opslaan in database om 19:28
- Excel kunnen aanroepen wanneer je wilt

**Comment by YannickdeZwart** [comment]
Ik zag ook dat die c3po bot ook mensen zelf berichtjes stuurt en ze pingt willen wij dat ook?

**Comment by rohid2000** [comment]
> Ik zag ook dat die c3po bot ook mensen zelf berichtjes stuurt en ze pingt willen wij dat ook?

Klopt ja, ja het ding is. Die C3PO bot wordt voor meerdere commands gebruikt.

- Tickets reminder, 2 uur voor reset
 - Mensen DM sturen daarmee
- Command om die toon stats en mods showen, waar Jonathan mee bezig is
- Command om de progress te monitoren die iemand heeft op een Journey Guide

Nou hebben wij al 3/4 bullet-points verwerkt in onze BOT, alleen die DM nog dan en die laatste bullet-point. Ik zou zeggen laten we kijken of we die laatste bullet-point ook kunnen maken en dan zouden we die C3PO bot gwn kunnen verwijderen uit de server en gwn alleen onze BOT gebruiken, wat op lange termijn sowieso ons idee was.
