### ISSUE TITLE
Refactor - based on tsom and tjom

### ISSUE THREAD

**Issue by rohid2000** [rohid2000/tsom-bot#70]

**Comment by YannickdeZwart** [comment]
ADD:
- config fields for guild_id

- config fields for channel ids

maybe whe split by a default rank that players have??
then add those 2 to the config.

otherwise whe can check for permissions.

Functionality:

 Tickets:
  - syncen apart???
  - excel / message apart??

Promotion:
  - split functionality


_______
Maybe a smart idea to add a command to edit channel ids for command feedback?

**Comment by rohid2000** [comment]
We could split by a default rank that players have: tsom and tjom, but I think that's gonna be an issue eventually, because at a point no one could have either of those roles. Because they will all be promoted eventually?

Tickets:

- Apart syncen
  - Lijkt me wel het beste om te doen, omdat we 2 guilds hebben met verschillende members in de guilds
  - Het is niet interessant voor beide Guilds om data/pings van de andere guild te zien
  - Excel apart
    - Lijkt me ook het beste om te doen, omdat we 2 guilds hebben met verschillende members in de guilds
    - Het is niet interessant voor beide Guilds om data/pings van de andere guild te zien

**Comment by YannickdeZwart** [comment]
Oke even een overzicht hoe alles nu werkt:

- tickets:
  - sync:
    - go | dit is per guild appart
    - check | dit is per guild appart
    - excel | hier worden gewoon de namen uit de excel uitgelezen (je zou dus 2 guilds in 1 excel kunnen teruggeven)
    - cleanup | ruimt alle data van beide guilds op
   - get:
    - excel | dit is per guild appart
    - message | dit is per guild appart
    - nvt | gaat op discord member dus maakt niet uit

- promotion:
per guild appart als je het sync. een override is per discord member dus maakt niet uit


Het zou wel chill zijn als iedereen een default rank zou hebben tjom of tsom. Hebben julllie iets daarover afgesproken anders moeten we er nog iets voor bouwen dat we die mensen uit elkaar houden.

**Comment by rohid2000** [comment]
Foutje, zie bij nog niet iedereen. Ga het nu goed zetten, zodat iedereen in ieder geval minimaal de tsom of tjom role heeft
